platform :osx, '10.12'
use_frameworks!

target 'Messenger478' do
    pod 'JSONWebToken', '~> 2.2.0'
    pod 'Socket.IO-Client-Swift', '~> 13.1.0'
    pod 'CryptoSwift', '~> 0.7.1'
    project '/Users/harrisonbalogh/Developer/Messenger478/Messenger478.xcodeproj'
end
